name: Pull Request Comment Trigger Example
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: theboolean/pull-request-comment-trigger@v0.3.2
        id: check
        with:
          trigger: '/simple'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'

  with_reaction:
    runs-on: ubuntu-latest
    steps:
      - uses: theboolean/pull-request-comment-trigger@v0.3.2
        id: check
        with:
          trigger: '#look'
          reaction: 'eyes'
          gh_token: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'

  prefix_only:
    runs-on: ubuntu-latest
    steps:
      - uses: theboolean/pull-request-comment-trigger@v0.3.2
        id: check
        with:
          prefix_only: 'true'
          trigger: '#deploy'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
      - run: 'echo Another step of the deploy job!'
        if: steps.check.outputs.triggered == 'true'